language: cpp
sudo: required
virtualenv:
    system_site_packages: true
git:
    submodules: false
    depth: 1
addons:
    homebrew:
        packages:
            - ccache
            - cmake
        update: true
cache: ccache
matrix:
  include:
    - os: osx
      osx_image: xcode11.2
      compiler: clang
      before_install:
        - git submodule update --init
        - sw_vers
        - python3 -m venv pyenv
        - source pyenv/bin/activate
      install:
        - pip install -r python/requirements.txt
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      before_install:
        - git submodule update --init
        - sw_vers
        - python3 -m venv pyenv
        - source pyenv/bin/activate
      install:
        - pip install -r python/requirements.txt
    - os: osx
      osx_image: xcode9.3
      compiler: clang
      before_install:
        - git submodule update --init
        - sw_vers
        - pip install virtualenv
        - virtualenv pyenv
        - source pyenv/bin/activate
      install:
        - pip install -r python/requirements.txt
script:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi
    - ccache --max-size=5.0G
    - ccache -V && ccache --show-stats && ccache --zero-stats
    - ./setup.py build
    - ./setup.py install
    - python -c "import pymesh; import sys; sys.exit(0 if pymesh.test().wasSuccessful() else 1)"
