version: 2

jobs:
  docker-image:
    machine: true
    steps:
      - checkout
      - run:
          name: Build versatile Docker image
          command: |
            docker build -f docker/Dockerfile --build-arg RUN_TESTS=1 -t pymesh/pymesh:latest .

workflows:
  version: 2
  build_and_test:
    jobs:
      - docker-image
